name: Azure
modes:
- name: normal
- name: normal_ro
buffers:

- !vbox
  name: root
  description: Root view
  bindings:
  # - name: open_resource_groups
  #   description: Open Resource Groups
  #   triggers:
  #   - "key <ControlR>"
  #   actions:
  #   - "/root/body/main.open"
  - name: close_current_buffer
    description: Open Resources for Logic Apps
    triggers:
    - "key q"
    actions:
    - "/close"
  - name: open_logic_apps
    description: Open Resources for Logic Apps
    triggers:
    - "key <ControlR>"
    actions:
    - "/root/body/main.open resources logic-apps"
  - name: open_resources
    description: Open Resources for Logic Apps
    triggers:
    - "key r"
    actions:
    - "/root/body/main.open resources TechInterview"
  - name: open_tech_interview
    description: Open Resources for Tech Interview
    triggers:
    - "key <ControlF>"
    actions:
    - "/root/body/main.open resources TechInterview"

  - name: close_view
    description: Close current view
    triggers:
    - "key Q"
    - "key <ControlC>"
    actions:
    - "quit"
  - name: focus_right
    description: Focus Right View
    scope: "/**"
    triggers:
    - "key <ControlL>"
    actions:
    - "/focusRight"
  - name: focus_left
    description: Focus Right View
    triggers:
    - "key <Backspace>"
    actions:
    - "/focusLeft"
  - name: focus_up
    description: Focus Up View
    # scope: "/**/sidebar/**"
    triggers:
    - "key <ControlK>"
    actions:
    - "/focusUp"
  - name: focus_down
    description: Focus Down View
    scope: "/**"
    triggers:
    - "key <ControlJ>"
    actions:
    - "/focusDown"
  - name: line_up
    description: Focus Previous Line
    scope: "/**"
    triggers:
    - "key k"
    actions:
    - "/lineUp"
  - name: line_down
    description: Focus Next Line
    scope: "/**"
    triggers:
    - "key j"
    actions:
    - "/lineDown"
  windows:
  - !buffer
    name: head
    value: menu
    height:
      mode: fixed
      fixed: 4
  # - !buffer
  #   name: menusplitter
  #   value: splitter
  #   height:
  #     mode: fixed
  #     fixed: 1
  - !buffer
    name: body
    value: body

- !table
  name: menu
  description: Application menu
  closable: false
  content:
    !list
    value:
    - menu

- !table
  name: sidebar
  description: Sidebar
  closable: false
  content:
    !list
    value:
    - sdb

- !hbox
  name: body
  description: Horizontal view with left sidebar and all the rest
  windows:
  - !buffer
    name: sidebar
    value: sidebar
    width:
      mode: fixed
      fixed: 7
  # - !buffer
  #   name: bodysplitter
  #   value: splitter
  #   width:
  #     mode: fixed
  #     fixed: 1
  - !buffer
    name: main
    value: main

- !hbox
  name: main
  description: Main container for content
  # closable: true
  # autoSplitters : false
  bindings:
  - name: focus_right
    description: Focus Right View
    # scope: "/*"
    triggers:
    - "key <ControlY>"
    actions:
    - "./focusRight"
  - name: focus_left
    description: Focus Right View
    scope: "./**"
    triggers:
    - "key <ControlT>"
    actions:
    - "./focusLeft"
  windows:
  - !buffer
    name: subscriptions
    value: subscriptions
  # - !buffer
  #   name: content2
  #   value: resource_groups
  # - !buffer
  #   name: content1
  #   value: resources

# - !splitter
#   name: splitter

- !table
  name: subscriptions
  description: List of subscriptions
  content:
    !cli
    input: az account list
    map: json_array_to_table
  bindings:
  - name: open_highlighted_resource_groups
    description: Open highlighted resource groups for subscription
    triggers:
    - "key <ControlM>"
    actions:
    - "/root/body/main.open resource_groups %(line.id)"
  columns:
  - name : name
    displayName : Name
  - name : cloudName
    displayName : Cloud Name

- !table
  name: resource_groups_basic
  description: List of resource groups for selected subscription
  parameters:
  - name: subscription
    type: string
    defaultValue: ""
  content:
    !cli
    input: az group list ?(subscription:--subscription) %(subscription)
    map: json_array_to_table
  columns:
  - name : name
    displayName : Name
  - name : location
    displayName : Az location

- !vbox
  name: resource_groups
  description: List of resource groups for selected subscription
  closable: true
  parameters:
  - name: subscription  
    type: string
    defaultValue: ""
  windows:
  - !buffer
    name: resource_groups_header
    value: resource_groups_header
    parameters:
    - name: subscription
      type: string
      defaultValue: "%(subscription)"
    height:
      mode: fixed
      fixed: 1
  - !buffer
    name: resource_groups_content
    value: resource_groups_content
    parameters:
    - name: subscription
      type: string
      defaultValue: "%(subscription)"

- !hbox
  name: resource_groups_content
  closable: false
  parameters:
  - name: subscription
    type: string
    defaultValue: ""
  windows:
  - !buffer
    name: resource_groups_sidebar
    value: resource_groups_sidebar
    parameters:
    - name: subscription
      type: string
      defaultValue: "%(subscription)"
    width:
      mode: fixed
      fixed: 5
  - !buffer
    name: resource_groups_table
    value: resource_groups_table
    parameters:
    - name: subscription
      type: string
      defaultValue: "%(subscription)"

- !table
  name: resource_groups_header
  description: Resource groups header
  closable: false
  focusable: false
  parameters:
  - name: subscription
    type: string
    defaultValue: ""
  content:
    !list
    value:
    - "%(subscription)"

- !table
  name: resource_groups_sidebar
  description: Resource groups sidebar
  closable: false
  content:
    !list
    value:
    - res
    - param
    - act

- !table
  name: resource_groups_table
  description: Table with list of resource groups
  closable: false
  bindings:
  - name: open_highlighted_resource
    description: Open highlighted resource
    triggers:
    - "key <ControlM>"
    actions:
    - "/root/body/main.open resources %(line.name)"
  parameters:
  - name: subscription
    type: string
    defaultValue: ""
  content:
    !cli
    input: az group list ?(subscription:--subscription) %(subscription)
    map: json_array_to_table
  columns:
  - name : name
    displayName : Name
  - name : location
    displayName : Az location

- !table
  name: resources_basic
  description: List of all resources
  parameters:
  - name: group  
    type: string
    defaultValue: ""
  content:
    !cli
    input: az resource list ?(group:--resource-group) %(group)
    map: json_array_to_table
  columns:
  - name : name
    displayName : Name
  - name : kind
    displayName : Kind
  - name : location
    displayName : Az location

- !vbox
  name: resources
  closable: true
  parameters:
  - name: group  
    type: string
    defaultValue: "TechInterview"
  windows:
  - !buffer
    name: resources_header
    value: resources_header
    parameters:
    - name: group  
      type: string
      defaultValue: "%(group)"
    height:
      mode: fixed
      fixed: 1
  - !buffer
    name: resources_content
    value: resources_content
    parameters:
    - name: group  
      type: string
      defaultValue: "%(group)"

- !hbox
  name: resources_content
  parameters:
  - name: group  
    type: string
    defaultValue: ""
  windows:
  - !buffer
    name: resources_sidebar
    value: resources_sidebar
    parameters:
    - name: group  
      type: string
      defaultValue: "%(group)"
    width:
      mode: fixed
      fixed: 5
  - !buffer
    name: resources_table
    value: resources_table
    parameters:
    - name: group
      type: string
      defaultValue: "%(group)"

- !table
  name: resources_header
  description: Resources header
  closable: false
  focusable: false
  parameters:
  - name: group
    type: string
    defaultValue: ""
  content:
    !list
    value:
    - "%(group)"

- !table
  name: resources_sidebar
  description: Resources sidebar
  closable: false
  content:
    !list
    value:
    - res
    - param
    - act

- !table
  name: resources_table
  description: Table view for list of all resources
  closable: false
  bindings:
  - name: open_highlighted_resource
    description: Open highlighted resource
    triggers:
    - "key <ControlM>"
    actions:
    - "/root/body/main.open resource_details %(line.id)"
  parameters:
  - name: group  
    type: string
    defaultValue: ""
  content:
    !cli
    input: az resource list ?(group:--resource-group) %(group)
    map: json_array_to_table
  columns:
  - name : name
    displayName : Name
  - name : kind
    displayName : Kind
  - name : location
    displayName : Az location

- !dict
  name: resource_details
  description: Details view for resource
  parameters:
  - name: resourceId  
    type: string
    defaultValue: ""
  content:
    !cli
    input: az resource show ?(resourceId:--ids) %(resourceId)
    map: json_object_to_dict
  columns:
  - name : name
    displayName : Name
  - name : kind
    displayName : Kind
  - name : location
    displayName : Az location
