name: test1
modes:
- name: normal
- name: normal_ro
buffers:

- !vbox
  name: root
  description: Root view
  content:
  - !buffer
    name: head
    value: menu
  - !buffer
    name: body
    value: body

- !hbox
  name: body
  description: Horizontal view with left sidebar and all the rest
  content:
  - !buffer
    name: sidebar
    value: sidebar
  - !buffer
    name: main
    value: main

- !hblade
  name: main
  description: Main container for content
  content:
  - !buffer
    name: content
    value: resource_groups


- !table
  name: resource_groups
  description: List of resource groups for selected subscription
  content:
  - !cli
    name: resource_groups
    cli:
      input: az group list
      map: json_array_to_table
      select:
      - name
      - location
      order:
      - name
      - location
