name: test3
modes:
- name: normal
- name: normal_ro
buffers:

- !vbox
  name: root
  description: Root view
  bindings:
  - name: command_mode
    description: Open command mode
    triggers:
    - "key :"
    actions:
    - "windows.cmd focus"
  windows:
  - !buffer
    name: head
    value: menu
    height:
      mode: fixed
      fixed: 4
  - !buffer
    name: body
    value: body

- !table
  name: menu
  description: Application menu
  content:
    !list
    value:
    - menu

- !table
  name: sidebar
  description: Sidebar
  content:
    !list
    value:
    - sdb

- !hbox
  name: body
  description: Horizontal view with left sidebar and all the rest
  windows:
  - !buffer
    name: sidebar
    value: sidebar
    width:
      mode: fixed
      fixed: 7
  - !buffer
    name: main
    value: main

- !hblade
  name: main
  description: Main container for content
  windows:
  - !buffer
    name: content
    value: resource_groups


- !table
  name: resource_groups
  description: List of resource groups for selected subscription
  content:
    !cli
    input: az group list
    map: json_array_to_table
    select:
    - name
    - location
    order:
    - name
    - location

