name: test3
modes:
- name: normal
- name: normal_ro
buffers:

- !vbox
  name: root
  description: Root view
  content:
  - !buffer
    name: head
    value: menu
    height:
      mode: fixed
      fixed: 1
  - !buffer
    name: body
    value: body

- !table
  name: menu
  description: Application menu
  cli:
    input: echo menu

- !table
  name: sidebar
  description: Sidebar
  cli:
    input: echo sdb

- !hbox
  name: body
  description: Horizontal view with left sidebar and all the rest
  content:
  - !buffer
    name: sidebar
    value: sidebar
    width:
      mode: fixed
      fixed: 7
  - !buffer
    name: main
    value: main

- !hblade
  name: main
  description: Main container for content
  content:
  - !buffer
    name: content
    value: resource_groups


- !table
  name: resource_groups
  description: List of resource groups for selected subscription
  cli:
    input: az group list
    map: json_array_to_table
    select:
    - name
    - location
    order:
    - name
    - location

