  - name: filter_start
    description: Focus filter field
    trigger: "key <ControlI>"
    actions:
    - "setMode filter"
    - "/filter"
  - name: filter_accept
    description: Accept filter
    trigger: "key <Enter>"
    actions:
    - "/filterAccept"
    - "setMode normal"
    mode: filter
  - name: filter_abort
    description: Abort filter
    trigger: "key <Esc>"
    actions:
    - "/filterAbort"
    - "setMode normal"
    mode: filter
  - name: filter_history_prev
    description: filter history previous
    trigger: "key <CursorUp>"
    action: "/filterHistoryPrev"
    mode: filter
  - name: filter_history_next
    description: filter history next
    trigger: "key <CursorDown>"
    action: "/filterHistoryNext"
    mode: filter
