  - name: search_start
    description: Focus search field
    trigger: "key /"
    actions:
    - "setMode search"
    - "/search"
  - name: search_accept
    description: Accept search
    trigger: "key <Enter>"
    actions:
    - "/searchAccept"
    - "setMode normal"
    mode: search
  - name: search_abort
    description: Abort search
    trigger: "key <Esc>"
    actions:
    - "/searchAbort"
    - "setMode normal"
    mode: search
  - name: search_history_prev
    description: Search history previous
    trigger: "key <CursorUp>"
    action: "/searchHistoryPrev"
    mode: search
  - name: search_history_next
    description: Search history next
    trigger: "key <CursorDown>"
    action: "/searchHistoryNext"
    mode: search
  - name: search_next
    description: Focus next search result
    trigger: "key n"
    action: "/focusNextResult"
  - name: search_prev
    description: Focus previous search result
    trigger: "key N"
    action: "/focusPrevResult"
