- !vbox
  name: {{ name }}
  description: {{ description }}
  closable: true
  bindings:
  - name: reload
    description: Reload current buffer
    trigger: "key R"
    action: "./reload"
  parameters:
{{#parameters}}
  - name: {{ this }}
    type: string
    defaultValue: ""
{{/parameters}}
  windows:
  - !buffer
    name: {{ name }}_header
    value: {{ name }}_header
    parameters:
{{#parameters}}
    - name: {{ this }}
      type: string
      defaultValue: "%({{ this }})"
{{/parameters}}
    height:
      mode: fixed
      fixed: 1
  - !buffer
    name: {{ name }}_content
    value: {{ name }}_content
    parameters:
{{#parameters}}
    - name: {{ this }}
      type: string
      defaultValue: "%({{ this }})"
{{/parameters}}
  content:
    !cli
    input: {{ cli }}
    map: json_array_to_table

- !hbox
  name: {{ name }}_content
  closable: false
  parameters:
{{#parameters}}
  - name: {{ this }}
    type: string
    defaultValue: ""
{{/parameters}}
  windows:
{{#if sidebar}}
  - !buffer
    name: {{ name }}_sidebar
    value: {{ name }}_sidebar
    parameters:
{{#parameters}}
    - name: {{ this }}
      type: string
      defaultValue: "%({{ this }})"
{{/parameters}}
    width:
      mode: fixed
      fixed: 5
{{/if}}
  - !buffer
    name: {{ name }}_table
    value: {{ name }}_table
    parameters:
{{#parameters}}
    - name: {{ this }}
      type: string
      defaultValue: "%({{ this }})"
{{/parameters}}

- !hbox
  name: {{ name }}_header
  description: {{ short_description }} header
  closable: false
  focusable: true
  parameters:
{{#parameters}}
  - name: {{ this }}
    type: string
    defaultValue: ""
{{/parameters}}
  windows:
  - !buffer
    name: {{ name }}_header_title
    value: {{ name }}_header_title
    parameters:
{{#parameters}}
    - name: {{ this }}
      type: string
      defaultValue: "%({{ this }})"
{{/parameters}}
  - !buffer
    name: {{ name }}_header_actions
    value: {{ name }}_header_actions

- !table
  name: {{ name }}_header_title
  description: {{ short_description }} header title
  closable: false
  focusable: false
  parameters:
{{#parameters}}
  - name: {{ this }}
    type: string
    defaultValue: ""
{{/parameters}}
  content:
    !list
    value:
    - "{{ header_value }}"

- !hactionlist
  name: {{ name }}_header_actions
  description: {{ short_description }} actions
  closable: false
  content:
    !actions
    value:
    - displayName: Reload
      action: "../../reload"
  bindings:
  - name: run_action
    description: run_selected_action
    trigger: "key <Enter>"
    action: "/runAction"

{{#if sidebar}}
- !table
  name: {{ name }}_sidebar
  description: {{ short_description }} sidebar
  closable: false
  content:
    !list
    value:
{{#sidebar}}
    - {{ this }}
{{/sidebar}}
{{/if}}

- !table
  name: {{ name }}_table
  description: Table with list of {{ short_description }}
  closable: false
  hasSearch: true
  defaultFocus: true
  bindings:
  - name: yank_id
    description: Yank id
    trigger: "key yi"
    action: "yank %(line.id)"
  - name: yank_name
    description: Yank name
    trigger: "key yn"
    action: "yank %(line.name)"
  - name: replace_with_highlighted_resource
    description: Replace view with highlighted resource
    trigger: "key gr"
    action: "{{ on_replace }}"
  - name: open_highlighted_resource
    description: Open highlighted resource
    trigger: "key <Enter>"
    action: "{{ on_enter }}"
{{#extra_bindings}}

  - name: {{ this.name }}
    description: {{ this.description }}
    trigger: {{ this.trigger }}
{{#exists 'action'}}
    action: {{ this.action }}
{{/exists}}
{{#exists 'actions'}}
    actions: {{ json 'actions' }}
{{/exists}}

{{/extra_bindings}}

{{#if highlight_url}}
  - name: open_highlight_in_browser
    description: Open hightlighted element in browser
    trigger: "key go"
    action: "openUrlInBrowser \"{{highlight_url}}\""
{{/if}}
{{#if current_url}}
  - name: open_current_view_in_browser
    trigger: "key gO"
    action: "openUrlInBrowser \"{{current_url}}\""
{{/if}}
{{> bindings/search.yml}}
{{> bindings/filter.yml}}
  parameters:
{{#parameters}}
  - name: {{ this }}
    type: string
    defaultValue: ""
{{/parameters}}
  # content:
  #   !cli
  #   input: {{ cli }}
  #   maps:
  #   - json_array_to_table
  content:
    !ref
    buffer: "../../"
    map: nop
  columns:
{{#columns}}
  - name : "{{ name }}"
    displayName : "{{ displayName }}"
{{#exists 'width'}}
    width: {{json 'width'}}
{{/exists}}
{{/columns}}
