- !vbox
  name: resource_groups
  description: List of resource groups for selected subscription
  closable: true
  parameters:
  - name: subscription  
    type: string
    defaultValue: ""
  windows:
  - !buffer
    name: resource_groups_header
    value: resource_groups_header
    parameters:
    - name: subscription
      type: string
      defaultValue: "%(subscription)"
    height:
      mode: fixed
      fixed: 1
  - !buffer
    name: resource_groups_content
    value: resource_groups_content
    parameters:
    - name: subscription
      type: string
      defaultValue: "%(subscription)"

- !hbox
  name: resource_groups_content
  closable: false
  parameters:
  - name: subscription
    type: string
    defaultValue: ""
  windows:
  - !buffer
    name: resource_groups_sidebar
    value: resource_groups_sidebar
    parameters:
    - name: subscription
      type: string
      defaultValue: "%(subscription)"
    width:
      mode: fixed
      fixed: 5
  - !buffer
    name: resource_groups_table
    value: resource_groups_table
    parameters:
    - name: subscription
      type: string
      defaultValue: "%(subscription)"

- !table
  name: resource_groups_header
  description: Resource groups header
  closable: false
  focusable: false
  parameters:
  - name: subscription
    type: string
    defaultValue: ""
  content:
    !list
    value:
    - "%(subscription)"

- !table
  name: resource_groups_sidebar
  description: Resource groups sidebar
  closable: false
  content:
    !list
    value:
    - res
    - param
    - act

- !table
  name: resource_groups_table
  description: Table with list of resource groups
  closable: false
  bindings:
  - name: open_highlighted_resource
    description: Open highlighted resource
    triggers:
    - "key <ControlM>"
    actions:
    - "/root/body/main.open resources %(line.name)"
  parameters:
  - name: subscription
    type: string
    defaultValue: ""
  content:
    !cli
    input: az group list ?(subscription:--subscription) %(subscription)
    map: json_array_to_table
  columns:
  - name : name
    displayName : Name
  - name : location
    displayName : Az location
