name: Azure
modes:
- name: normal
- name: normal_ro
buffers:

- !vbox
  name: root
  description: Root view
  bindings:
  # - name: open_resource_groups
  #   description: Open Resource Groups
  #   triggers:
  #   - "key <ControlR>"
  #   actions:
  #   - "/root/body/main.open"
  - name: close_current_buffer
    description: Open Resources for Logic Apps
    triggers:
    - "key q"
    actions:
    - "/close"
  - name: close_view
    description: Close current view
    triggers:
    - "key Q"
    - "key <ControlC>"
    actions:
    - "quit"
  - name: focus_right
    description: Focus Right View
    scope: "/**"
    triggers:
    - "key <ControlL>"
    actions:
    - "/focusRight"
  - name: focus_left
    description: Focus Right View
    triggers:
    - "key <Backspace>"
    actions:
    - "/focusLeft"
  - name: focus_up
    description: Focus Up View
    triggers:
    - "key <ControlK>"
    actions:
    - "/focusUp"
  - name: focus_down
    description: Focus Down View
    scope: "/**"
    triggers:
    - "key <ControlJ>"
    actions:
    - "/focusDown"
  - name: line_up
    description: Focus Previous Line
    scope: "/**"
    triggers:
    - "key k"
    actions:
    - "/lineUp"
  - name: line_down
    description: Focus Next Line
    scope: "/**"
    triggers:
    - "key j"
    actions:
    - "/lineDown"
  windows:
  - !buffer
    name: head
    value: menu
    height:
      mode: fixed
      fixed: 4
  # - !buffer
  #   name: menusplitter
  #   value: splitter
  #   height:
  #     mode: fixed
  #     fixed: 1
  - !buffer
    name: body
    value: body

- !table
  name: menu
  description: Application menu
  closable: false
  content:
    !list
    value:
    - menu

- !table
  name: sidebar
  description: Sidebar
  closable: false
  content:
    !list
    value:
    - sdb

- !hbox
  name: body
  description: Horizontal view with left sidebar and all the rest
  windows:
  - !buffer
    name: sidebar
    value: sidebar
    width:
      mode: fixed
      fixed: 7
  # - !buffer
  #   name: bodysplitter
  #   value: splitter
  #   width:
  #     mode: fixed
  #     fixed: 1
  - !buffer
    name: main
    value: main

- !hbox
  name: main
  description: Main container for content
  # closable: true
  # autoSplitters : false
  bindings:
  - name: focus_right
    description: Focus Right View
    # scope: "/*"
    triggers:
    - "key <ControlY>"
    actions:
    - "./focusRight"
  - name: focus_left
    description: Focus Right View
    scope: "./**"
    triggers:
    - "key <ControlT>"
    actions:
    - "./focusLeft"
  windows:
  - !buffer
    name: subscriptions
    value: subscriptions

- !table
  name: subscriptions
  description: List of subscriptions
  content:
    !cli
    input: az account list
    map: json_array_to_table
  bindings:
  - name: open_highlighted_resource_groups
    description: Open highlighted resource groups for subscription
    triggers:
    - "key <ControlM>"
    actions:
    - "/root/body/main.open resource_groups %(line.id)"
  columns:
  - name : name
    displayName : Name
  - name : cloudName
    displayName : Cloud Name

{{#complex_buffers}}
{{> buffers/complex_buffer.yml}}
{{/complex_buffers}}

- !dict
  name: resource_details
  description: Details view for resource
  parameters:
  - name: resourceId  
    type: string
    defaultValue: ""
  content:
    !cli
    input: az resource show ?(resourceId:--ids) %(resourceId)
    map: json_object_to_dict
  columns:
  - name : name
    displayName : Name
  - name : kind
    displayName : Kind
  - name : location
    displayName : Az location
