name: Azure
modes:
- name: normal
- name: normal_ro
- name: nav
- name: search
buffers:

- !vbox
  name: root
  description: Root view
  bindings:
  # - name: open_resource_groups
  #   description: Open Resource Groups
  #   triggers:
  #   - "key <ControlR>"
  #   actions:
  #   - "/root/body/main.open"
  - name: nop
    description: Override default action
    triggers:
    - "key <CursorLeft>"
    - "key <CursorRight>"
    - "key <Tab>"
    - "key <BackTab>"
    action: "nop"
  - name: return_to_normal_mode
    description: Return to normal mode from nav mode
    trigger: "key <Esc>"
    action: "setMode normal"
    mode: nav
  - name: nav_mode
    description: Start nav mode
    trigger: "key ("
    action: "setMode nav"
  - name: focus_right_nav
    description: Focus Right View in nav mode
    scope: "/**"
    trigger: "key l"
    action: "/focusRight"
    mode: nav
  - name: focus_left_nav
    description: Focus Right View in nav mode
    trigger: "key h"
    action: "/focusLeft"
    mode: nav
  - name: focus_up_nav
    description: Focus Up View in nav mode
    trigger: "key k"
    action: "/focusUp"
    mode: nav
  - name: focus_down_nav
    description: Focus Down View in nav mode
    scope: "/**"
    trigger: "key j"
    action: "/focusDown"
    mode: nav


  - name: replace_with_subscriptions
    description: Replace main with with subscriptions
    trigger: "key rsub"
    action: "/root/body/main.replace subscriptions"
  - name: clear_key_stack
    description: Clear key chord stack
    trigger: "key <Esc>"
    action: "clearKeyStack"
  - name: close_current_buffer
    description: Open Resources for Logic Apps
    trigger: "key q"
    action: "/close"
  - name: close_view
    description: Close current view
    triggers:
    - "key Q"
    - "key <ControlC>"
    action: "quit"
  - name: focus_right
    description: Focus Right View
    scope: "/**"
    triggers:
    - "key <ControlL>"
    - "key gl"
    action: "/focusRight"
  - name: focus_left
    description: Focus Right View
    triggers:
    - "key <ControlH>"
    - "key gh"
    action: "/focusLeft"
  - name: focus_up
    description: Focus Up View
    triggers:
    - "key <ControlK>"
    - "key gk"
    action: "/focusUp"
  - name: focus_down
    description: Focus Down View
    scope: "/**"
    triggers:
    - "key <ControlJ>"
    - "key gj"
    action: "/focusDown"
  - name: line_up
    description: Focus Previous Line
    scope: "/**"
    trigger: "key k"
    action: "/lineUp"
  - name: line_down
    description: Focus Next Line
    scope: "/**"
    trigger: "key j"
    action: "/lineDown"
  - name: line_first
    description: Focus First Line
    scope: "/**"
    trigger: "key gg"
    action: "/lineFirst"
  - name: line_last
    description: Focus Last Line
    scope: "/**"
    trigger: "key G"
    action: "/lineLast"

  - name: column_left
    description: Focus Previous column
    scope: "/**"
    trigger: "key h"
    action: "/columnLeft"
  - name: column_right
    description: Focus Next column
    scope: "/**"
    trigger: "key l"
    action: "/columnRight"
  - name: column_first
    description: Focus First column
    scope: "/**"
    trigger: "key _"
    action: "/columnFirst"
  - name: column_last
    description: Focus Last column
    scope: "/**"
    trigger: "key $"
    action: "/columnLast"
  windows:
  - !buffer
    name: head
    value: menu
    height:
      mode: fixed
      fixed: 4
  # - !buffer
  #   name: menusplitter
  #   value: splitter
  #   height:
  #     mode: fixed
  #     fixed: 1
  - !buffer
    name: body
    value: body


- !hactionlist
  name: menu
  description: Application menu
  closable: false
  content:
    !actions
    value:
    - displayName: SB
      action: "/root/body/main.replace subscriptions"
    - displayName: RG
      action: "/root/body/main.replace resources"
  bindings:
  - name: run_action
    description: run_selected_action
    trigger: "key <Enter>"
    action: "/runAction"

- !vactionlist
  name: sidebar
  description: Sidebar
  closable: false
  content:
    !actions
    value:
    - displayName: SB
      action: "/root/body/main.replace subscriptions"
    - displayName: RG
      action: "/root/body/main.replace resources"
  bindings:
  - name: run_action
    description: run_selected_action
    trigger: "key <Enter>"
    action: "/runAction"
{{> bindings/search.yml}}



- !hbox
  name: body
  description: Horizontal view with left sidebar and all the rest
  windows:
  - !buffer
    name: sidebar
    value: sidebar
    width:
      mode: fixed
      fixed: 7
  # - !buffer
  #   name: bodysplitter
  #   value: splitter
  #   width:
  #     mode: fixed
  #     fixed: 1
  - !buffer
    name: main
    value: main

- !stack
  name: main
  description: Main container for content
  # closable: true
  # autoSplitters : false
  bindings:
  - name: focus_right
    description: Focus Right View
    # scope: "/*"
    trigger: "key <ControlY>"
    action: "./focusRight"
  - name: focus_left
    description: Focus Right View
    scope: "./**"
    trigger: "key <ControlT>"
    action: "./focusLeft"
  windows:
  - !buffer
    name: subscriptions
    value: subscriptions

{{#complex_buffers}}
{{> buffers/complex_buffer.yml}}
{{/complex_buffers}}

- !dict
  name: resource_details
  description: Details view for resource
  parameters:
  - name: resourceId  
    type: string
    defaultValue: ""
  content:
    !cli
    input: az resource show ?(resourceId:--ids) %(resourceId)
    map: json_object_to_dict
  columns:
  - name : name
    displayName : Name
  - name : kind
    displayName : Kind
  - name : location
    displayName : Az location
