complex_buffers:
- name: resource_groups
  short_description: Resource groups
  description: List of resource groups for selected subscription
  parameters:
  - subscription
  - tenantId
  cli: "az group list ?(subscription:--subscription) %(subscription)"
  highlight_url: "https://portal.azure.com/#@%(tenantId)/resource%(line.id)"
  current_url: "https://portal.azure.com/#@%(tenantId)/resource/subscriptions/%(subscription)/resourceGroups"
  on_enter: "/root/body/main.replace_subsequent resources %(line.name)"
  on_replace: "/root/body/main.replace resources %(line.name)"
  header_value: "%(subscription)"
  columns:
  - name : name
    displayName : Name
  - name : location
    displayName : Az location
  sidebar:
  - res
  - param
  - act
- name: resources
  short_description: Resources
  description: List of resources in resource group
  parameters:
  - group
  cli: "az resource list ?(group:--resource-group) %(group)"
  on_enter: "/root/body/main.replace_subsequent resource_details %(line.id)"
  on_replace: "/root/body/main.replace resource_details %(line.id)"
  header_value: "%(group)"
  columns:
  - name : name
    displayName : Name
  - name : kind
    displayName : Kind
  - name : location
    displayName : Az location
  sidebar:
  - res
  - wha
- name: subscriptions
  short_description: Subscriptions
  description: List of subscriptions
  cli: "az account list --all"
  highlight_url: "https://portal.azure.com/#@%(line.tenantId)/resource/subscriptions/%(line.id)/overview"
  current_url: "https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade"
  on_enter: "/root/body/main.replace_subsequent resource_groups %(line.id) %(line.tenantId)"
  on_replace: "/root/body/main.replace resource_groups %(line.id) %(line.tenantId)"
  header_value: "Subscriptions"
  columns:
  - name : name
    displayName : Name
  - name : isDefault
    displayName : Default
    width:
      mode: auto
      fillRatio: 0
  - name : cloudName
    displayName : Cloud Name
    width:
      mode: auto
      fillRatio: 0

bindings:
- keys: "j"
  action: "/lineDown"
- keys: "k"
  action: "/lineUp"